baseURL: https://ernesto.arbitrio.fyi
languageCode: en-us
title: Ernesto Arbitrio
schema: true
permalinks:
  page:
    posts: /posts/:slug/
pagination.pagerSize: 5
services:
  rss:
    limit: 30
  googleAnalytics:
    id: G-L18ZJ5LY2H
uglyURLs: false
