main:
  - name: Home
    pageRef: /
    weight: 10
  - name: About
    pageRef: /about
    weight: 20

social:
  - identifier: "github"
    name: "GitHub"
    url: "https://github.com/ernestoarbitrio"
    weight: 10
    params:
      icon: "brand-github"
  - identifier: "mastodon"
    name: "Mastodon"
    url: "https://mastodon.social/@pamaron"
    weight: 20
    params:
      icon: "brand-mastodon"
  - identifier: "linkedin"
    name: "LinkedIn"
    url: "https://www.linkedin.com/in/ernestoarbitrio"
    weight: 30
    params:
      icon: "brand-linkedin"
  - identifier: "rss"
    name: "RSS"
    url: "/index.xml"
    weight: 40
    params:
      icon: "rss"
